import argparse
import sys
import datetime
from outlook import Outlook

parser = argparse.ArgumentParser()
parser.add_argument('-s', '--sendEmail', required=False, default=False)
namespace = parser.parse_args(sys.argv[1:])

print("NUMBER OF ARGUMENTS: ", len(sys.argv))
print("ARGUMENTS: ", str(sys.argv))


print("---- START ----")

print("\n---- CREATE Outlook Object ----")
mailbox = Outlook(username='covidconnect2020@outlook.com', password='mithack10')

if namespace.sendEmail:
    print("\n--- SEND EMAIL ---")
    mailbox.send_email([namespace.sendEmail], "TEST_EMAIL_SUBJECT", "THIS MESSAGE WAS AUTOGENERATED VIA PYTHON AT %s" % datetime.datetime.now())

print("\n---- END ----")
